# Generated by Django 3.2 on 2021-08-22 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('content', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('choice', models.JSONField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNum', models.IntegerField(default=0)),
                ('matchType', models.CharField(choices=[('mf', 'male->female'), ('mm', 'male->male'), ('ff', 'female->female')], default='mf', max_length=2)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('femaleNumForMale', models.IntegerField(default=0)),
                ('maleNumForFemale', models.IntegerField(default=0)),
                ('femaleNumForFemale', models.IntegerField(default=0)),
                ('maleNumForMale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isBanned', models.BooleanField(default=False)),
                ('isWaiting', models.BooleanField(default=False)),
                ('inRoom', models.BooleanField(default=False)),
                ('matchType', models.CharField(choices=[('mf', 'male->female'), ('fm', 'female->male'), ('mm', 'male->male'), ('ff', 'female->female')], default=None, max_length=2, null=True)),
                ('result', models.JSONField(default=None, max_length=100, null=True)),
                ('waitingTime', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room')),
                ('school', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.school')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.player')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.JSONField(max_length=200)),
                ('action', models.CharField(max_length=30)),
                ('sub', models.CharField(default=None, max_length=10, null=True)),
                ('number', models.IntegerField()),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.robot')),
            ],
        ),
    ]
