# Generated by Django 3.2 on 2022-03-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hasDifferentEvents',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='hasDifferentRoles',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='noplayerNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='showGender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
