# Generated by Django 3.2 on 2022-01-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='sub',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gamerole',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tag_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='onoff_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='player_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
