# Generated by Django 3.2 on 2022-01-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220121_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploader',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
