# Generated by Django 3.2 on 2022-03-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220303_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hasDifferentEvents',
        ),
        migrations.RemoveField(
            model_name='game',
            name='hasDifferentRoles',
        ),
        migrations.AlterField(
            model_name='player',
            name='match',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='chat.match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='chat.room'),
        ),
    ]
