# Generated by Django 3.2 on 2021-09-08 04:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_dialogue_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='dialog',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
