# Generated by Django 3.2 on 2021-09-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_dialogue_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='dialog',
            field=models.JSONField(null=True),
        ),
    ]
