# Generated by Django 3.2 on 2022-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_photo_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
