# Generated by Django 3.2 on 2021-09-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_dialogue_dialog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='url',
        ),
    ]
