# Generated by Django 3.2 on 2022-03-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_game_noplayernum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='noplayerNum',
            new_name='NoPlayerNum',
        ),
    ]
