# Generated by Django 3.2 on 2021-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_school_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploader',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
