# Generated by Django 3.2 on 2022-03-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_noplayernum_game_noplayernum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='NoPlayerNum',
            new_name='noPlayerNum',
        ),
    ]
