# Generated by Django 3.2 on 2021-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_photo_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploader',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
