# Generated by Django 3.2 on 2021-10-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_photo_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='result',
            new_name='testResult',
        ),
        migrations.AddField(
            model_name='player',
            name='inTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='matchType',
            field=models.CharField(choices=[('mf', 'male->female'), ('mm', 'male->male'), ('ff', 'female->female')], max_length=2),
        ),
    ]
