# Generated by Django 3.2 on 2021-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211004_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='waitingTime',
        ),
        migrations.AddField(
            model_name='player',
            name='waiting_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
