# Generated by Django 3.2 on 2021-10-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20211004_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='inRoom',
        ),
        migrations.RemoveField(
            model_name='player',
            name='inTest',
        ),
        migrations.RemoveField(
            model_name='player',
            name='isWaiting',
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
