# Generated by Django 3.2 on 2021-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20211006_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='anonName',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
