# Generated by Django 3.2 on 2021-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20211025_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='roomNum',
            field=models.IntegerField(default=0),
        ),
    ]
