# Generated by Django 3.2 on 2021-11-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20211101_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
