# Generated by Django 3.2 on 2021-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='isForAdult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='imgUrl_adult',
            field=models.URLField(default=None, null=True),
        ),
    ]
