# Generated by Django 3.2 on 2021-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
