# Generated by Django 3.2 on 2021-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_player_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default=None, max_length=1, null=True),
        ),
    ]
