# Generated by Django 3.2 on 2021-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_player_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('isAdult', models.BooleanField()),
                ('isHetero', models.BooleanField()),
                ('best_ratio', models.JSONField(max_length=10)),
                ('threshold_ratio', models.JSONField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='imgUrl_adult',
            field=models.URLField(null=True),
        ),
    ]
