# Generated by Django 3.2 on 2021-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20211128_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='sub',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploader',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='anonName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='matchType',
            field=models.CharField(choices=[('mf', 'male->female'), ('fm', 'female->male'), ('mm', 'male->male'), ('ff', 'female->female')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='testResult',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='waiting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
