# Generated by Django 3.2 on 2021-11-29 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20211128_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isAdult',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='isHetero',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='playerNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='onoff_list',
            field=models.JSONField(default=dict, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='player_list',
            field=models.JSONField(default=dict, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game')),
            ],
        ),
    ]
