# Generated by Django 3.2 on 2021-11-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20211129_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='GameRole',
        ),
    ]
