# Generated by Django 3.2 on 2021-11-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_rename_role_gamerole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='onoff_list',
            new_name='onoff_dict',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='player_list',
            new_name='player_dict',
        ),
        migrations.RemoveField(
            model_name='room',
            name='femaleNeeded',
        ),
        migrations.RemoveField(
            model_name='room',
            name='isFull',
        ),
        migrations.RemoveField(
            model_name='room',
            name='maleNeeded',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
        migrations.AddField(
            model_name='player',
            name='isPrepared',
            field=models.BooleanField(default=False),
        ),
    ]
