# Generated by Django 3.2 on 2021-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20211129_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
