# Generated by Django 3.2 on 2021-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tag_json',
            field=models.JSONField(max_length=25, null=True),
        ),
    ]
