# Generated by Django 3.2 on 2021-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_player_tag_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isOn',
            field=models.BooleanField(default=False),
        ),
    ]
