# Generated by Django 3.2 on 2021-12-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_player_ison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='registered',
            new_name='isRegistered',
        ),
    ]
