# Generated by Django 3.2 on 2021-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_rename_registered_player_isregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='isAdult',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='isHetero',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
