# Generated by Django 3.2 on 2021-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_auto_20211202_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
