# Generated by Django 3.2 on 2021-12-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_auto_20211203_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerole',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(null=True)),
                ('group', models.IntegerField(default=0)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game')),
            ],
        ),
    ]
