# Generated by Django 3.2 on 2021-12-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_auto_20211203_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
        migrations.AddField(
            model_name='room',
            name='answer',
            field=models.JSONField(default=dict, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.school'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20, null=True)),
                ('player_list', models.JSONField(default=list, max_length=200, null=True)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.match'),
        ),
    ]
