# Generated by Django 3.2 on 2021-12-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_auto_20211208_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='school',
        ),
    ]
