# Generated by Django 3.2 on 2021-12-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_remove_room_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.school'),
        ),
    ]
