# Generated by Django 3.2 on 2021-12-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0035_room_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='gamerole',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='chat.game'),
        ),
    ]
