# Generated by Django 3.2 on 2021-12-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_auto_20211210_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='gamerole',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
        migrations.AlterField(
            model_name='room',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
    ]
