# Generated by Django 3.2 on 2021-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_auto_20211210_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='gameId',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
