# Generated by Django 3.2 on 2021-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_auto_20211210_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
