# Generated by Django 3.2 on 2021-12-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_auto_20211210_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
    ]
