# Generated by Django 3.2 on 2021-12-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_remove_dialogue_speaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
    ]
