# Generated by Django 3.2 on 2021-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_auto_20211211_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('roomNum', models.IntegerField(default=0)),
                ('femaleNumForMale', models.IntegerField(default=0)),
                ('maleNumForFemale', models.IntegerField(default=0)),
                ('femaleNumForFemale', models.IntegerField(default=0)),
                ('maleNumForMale', models.IntegerField(default=0)),
            ],
        ),
    ]
