# Generated by Django 3.2 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0041_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='story',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_list',
            field=models.JSONField(default=list, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='answer',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
