# Generated by Django 3.2 on 2022-01-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_auto_20211231_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.city', to_field='name'),
        ),
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.city', to_field='name'),
        ),
    ]
