# Generated by Django 3.2 on 2022-01-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0045_auto_20220112_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='school',
        ),
        migrations.RemoveField(
            model_name='room',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
