# Generated by Django 3.2 on 2022-01-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0047_alter_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isRegistered',
        ),
    ]
